/* config.h - Generated by CMake for dfu-util */

#ifndef CONFIG_H
#define CONFIG_H

/* Package information */
#define PACKAGE "dfu-util"
#define PACKAGE_VERSION "0.11"
#define PACKAGE_STRING "dfu-util 0.11"
#define PACKAGE_BUGREPORT "https://sourceforge.net/p/dfu-util/tickets/"

/* Platform capabilities - set by CMakeLists.txt via add_definitions */
/* HAVE_CONFIG_H is defined */
/* HAVE_UNISTD_H is defined on Unix */
/* HAVE_NANOSLEEP is defined on Unix */
/* HAVE_ERR is defined on Unix */
/* HAVE_SYSEXITS_H is defined on Unix */
/* HAVE_WINDOWS_H is defined on Windows */

/* Standard types */
#include <stdint.h>
#include <sys/types.h>

#endif /* CONFIG_H */
